towerNames = {
    "Huntington": "Huntington (All Saints), North Yorkshire",
    "Arts Centre": "York (Former St John (Arts Center)), Yorkshire",
    "Minster": "York (Cathedral and Metropolitical Church of St Peter), North Yorkshire",
    "Minster (Ringing Chamber)": "York (Ringing Chamber, Cathedral and Metropolitical Church of St Peter), North Yorkshire",
    "Minster (Clock Chamber)": "York (Clock Chamber, SW tower, Cathedral and Metropolitical Church of St Peter), North Yorkshire",
    "St Lawrence": "York (St Lawrence), North Yorkshire",
    "St Martin le Grand": "York (St Martin le Grand, Coney Street), North Yorkshire",
    "Stockton-on-the-Forest": "Stockton-on-the-Forest (Holy Trinity), North Yorkshire",
    "St Wilfrids": "York (Oratory Church of St Wilfrid), North Yorkshire",
    "Clifton": "York (St Philip and St James, Clifton), North Yorkshire",
    "Spurriergate": "York (Spurriergate Centre), North Yorkshire",
    "Bishopthorpe": "York (St Andrew, Bishopthorpe), North Yorkshire",
    "St Olave": "York (St Olave, Marygate), North Yorkshire",
    "Acomb": "Acomb (St Stephen), North Yorkshire",
    "North Street": "York (All Saints, North Street), North Yorkshire",
    "Bedale": "Bedale (St Gregory), North Yorkshire",
    "Nunburnholme": "Nunburnholme (St James), East Riding of Yorkshire",
    "Strensall": "Strensall (St Mary the Virgin), North Yorkshire",
    "Barnoldswick": "Barnoldswick (St Mary le Ghyll), Lancashire",
    "Broughton in Craven": "Broughton in Craven (All Saints), North Yorkshire",
    "Holme on Spalding Moor": "Holme on Spalding Moor (All Saints), East Riding of Yorkshire",
    "Inveraray": "Inveraray (All Saints), Argyll and Bute",
    "Kirby Hill": "Kirby Hill (All Saints), North Yorkshire",
    "Pontefract": "Pontefract (All Saints), West Yorkshire",
    "Rufforth": "Rufforth (All Saints), North Yorkshire",
    "Thorpe Arch": "Thorpe Arch (All Saints), West Yorkshire",
    "Yatesbury": "Yatesbury (All Saints), Wiltshire	",
    "East Campus": "University of York (East Campus), North Yorkshire",
    "Brewster": "Brewster (Melrose School), New York",
    "Dunkirk": "Dunkirk (Red Light Ring), Nottinghamshire",
    "Pontefract (St Giles)": "Pontefract (St Giles), West Yorkshire",
    "West Bridgford": "West Bridgford (St Giles), Nottinghamshire",
    "Ainderby Steeple": "Ainderby Steeple (St Helen), North Yorkshire",
    "Escrick": "Escrick (St Helen), North Yorkshire",
    "Birstwith": "Birstwith (St James the Apostle), North Yorkshire",
    "St John's College": "York (St John's College), North Yorkshire",
    "Seale": "Seale (St Lawrence), Surrey",
    "Bilborough": "Bilborough (St Martin of Tours), Nottinghamshire",
    "Chieveley": "Chieveley (St Mary the Virgin), Berkshire",
    "Beenham": "Beenham (St Mary), Berkshire",
    "Wath": "Wath juxta Ripon (St Mary), North Yorkshire",
    "Weldon": "Weldon (St Mary), Northamptonshire",
    "Midgham": "Midgham (St Matthew), Berkshire",
    "Pirbright": "Pirbright (St Michael), Surrey",
    "Yorktown": "Yorktown (St Michael), Surrey",
    "Chiswick": "Chiswick (St Nicholas), Greater London",
    "Newbury": "Newbury (St Nicolas), Berkshire",
    "Horton in Ribblesdale": "Horton in Ribblesdale (St Oswald), North Yorkshire",
    "Marton in Craven": "Marton in Craven (St Peter), North Yorkshire",
    "Upper Helmsley": "Upper Helmsley (St Peter), North Yorkshire",
    "Harrogate": "Harrogate (St Wilfrids), North Yorkshire",
    "Rochester": "Rochester (The Ascension), New York",
    "Ringing Room": "Ringing Room, UK",
    "Richmond": "Richmond, North Yorkshire",
    "Baskerville": "Baskerville House (Lichfield Diocesan Mobile Belfry), Staffordshire",
    "532 Norwich Road": "Ipswich (532 Norwich Road (The Vestey Ring)), Suffolk",
    "35 Willis Street": "York (35 Willis Street), North Yorkshire",
    "61 Fox Street": "Warrington (61 Fox Street)",
}

locationSynonyms = {
    "All Saints, Huntington, York, North Yorkshire": towerNames["Huntington"],
    "All Saints, Huntington, North Yorkshire": towerNames["Huntington"],
    "Art's Centre, York, North Yorkshire": towerNames["Arts Centre"],
    "Arts Centre, Micklegate, York, North Yorkshire": towerNames["Arts Centre"],
    "Arts Centre, York, North Yorkshire": towerNames["Arts Centre"],
    "Former St John (Arts Center), York, Yorkshire": towerNames["Arts Centre"],
    "Former St John, York, North Yorkshire": towerNames["Arts Centre"],
    "Tiger 10 (a ka The Parish, fomerly St John, Ousebridge), York, N Yorkshire": towerNames["Arts Centre"],
    "Cathedral and Metropolitical Church of St Peter, York, North Yorkshire": towerNames["Minster"],
    "Cathedral & Metropolitical Church of St Peter, York, North Yorkshire": towerNames["Minster"],
    "Minster, York, North Yorkshire": towerNames["Minster"],
    "Minster (clock chamber, SW tower), York, ": towerNames["Minster (Clock Chamber)"],
    "Minster (Ringing Chamber), York, ": towerNames["Minster (Ringing Chamber)"],
    "St Lawrence, York, North Yorkshire": towerNames["St Lawrence"],
    "St Lawrence, York, ": towerNames["St Lawrence"],
    "St Lawrence, York, Yorkshire": towerNames["St Lawrence"],
    "St Lawrence, York, N Yorkshire": towerNames["St Lawrence"],
    ", York (St Lawrence), N Yorkshire": towerNames["St Lawrence"],
    "York (St. Lawrence), North Yorkshire": towerNames["St Lawrence"],
    ", York (St. Lawrence), North Yorkshire": towerNames["St Lawrence"],
    ", York St Laurence, North Yorkshire": towerNames["St Lawrence"],
    "St Laurence, Hull Road, York, ": towerNames["St Lawrence"],
    "St Laurence, York, ": towerNames["St Lawrence"],
    "St Laurence, York, N Yorkshire": towerNames["St Lawrence"],
    "St Laurence, York, N. Yorkshire": towerNames["St Lawrence"],
    "St Laurence, York, North Yorkshire": towerNames["St Lawrence"],
    "St Laurence, York, Yorkshire": towerNames["St Lawrence"],
    "St Martin le Grand, York, North Yorkshire": towerNames["St Martin le Grand"],
    "St Martin Le Grand, York, Yorkshire": towerNames["St Martin le Grand"],
    "St Martin-le-Grand, Coney Street, York, North Yorkshire": towerNames["St Martin le Grand"],
    "St Martin le Grand (Coney Street), York, North Yorkshire": towerNames["St Martin le Grand"],
    "St Martin le Grand, Coney Street, York, ": towerNames["St Martin le Grand"],
    "St Martin le Grand, Coney Street, York, North Yorkshire": towerNames["St Martin le Grand"],
    "St Martin le Grand, York, ": towerNames["St Martin le Grand"],
    "St Martin, York, N Yorkshire": towerNames["St Martin le Grand"],
    "St Martin-le-Grand, York, ": towerNames["St Martin le Grand"],
    "St Martin-le-Grand, York, N.Yorkshire": towerNames["St Martin le Grand"],
    "Holy Trinity, Stockton on the Forest, North Yorkshire": towerNames["Stockton-on-the-Forest"],
    "Holy Trinity, Stockton-on-the-Forest, North Yorkshire": towerNames["Stockton-on-the-Forest"],
    "St Wilfrid RC, York, North Yorkshire": towerNames["St Wilfrids"],
    "St Wilfrid, York, North Yorkshire": towerNames["St Wilfrids"],
    "St Wilfrid, York, ": towerNames["St Wilfrids"],
    "St Wilfrid, York, N Yorkshire": towerNames["St Wilfrids"],
    "St Wilfrid, York, N. Yorkshire": towerNames["St Wilfrids"],
    "Oratory Church of St Wilfrid, York, North Yorkshire": towerNames["St Wilfrids"],
    "SS Philip & James, Clifton, York, ": towerNames["Clifton"],
    "SS Philip and James, Clifton, York, ": towerNames["Clifton"],
    "SS Philip and James, Clifton, York, N Yorkshire": towerNames["Clifton"],
    "SS Philip and James, Clifton, York, North Yorkshire": towerNames["Clifton"],
    "St Philip and St James, Clifton, North Yorkshire": towerNames["Clifton"],
    "St Philip and St James, Clifton, York, North Yorkshire": towerNames["Clifton"],
    "Spurriergate (St Michael), York, N Yorkshire": towerNames["Spurriergate"],
    "Spurriergate Centre (Formerly St Michael), York, North Yorkshire": towerNames["Spurriergate"],
    "Spurriergate Centre, York, ": towerNames["Spurriergate"],
    "Spurriergate Centre, York, North Yorkshire": towerNames["Spurriergate"],
    "Spurriergate Centre, York, Yorkshire": towerNames["Spurriergate"],
    "Spurriergate, York, ": towerNames["Spurriergate"],
    "St Michael, Spurriergate, York, N Yorkshire": towerNames["Spurriergate"],
    "St Michael, Spurriergate, York, North Yorkshire": towerNames["Spurriergate"],
    "Spurriergate, York, North Yorkshire": towerNames["Spurriergate"],
    "St Andrew, Bishopthorpe, North Yorkshire": towerNames["Bishopthorpe"],
    "St Andrew, Bishopthorpe, York, North Yorkshire": towerNames["Bishopthorpe"],
    "St Andrew, York (Bishopthorpe), ": towerNames["Bishopthorpe"],
    "St Olave, Marygate, York, North Yorkshire": towerNames["St Olave"],
    "St Olave, York, ": towerNames["St Olave"],
    "St Olave, York, N Yorkshire": towerNames["St Olave"],
    "St Olave, York, North Yorkshire": towerNames["St Olave"],
    "St Stephen, Acomb, North Yorkshire": towerNames["Acomb"],
    "All Saints, North Street, York, North Yorkshire": towerNames["North Street"],
    "St Gregory, Bedale, North Yorkshire": towerNames["Bedale"],
    "St James, Nunburnholme, East Riding of Yorkshire": towerNames["Nunburnholme"],
    "St Mary the Virgin, Strensall, North Yorkshire": towerNames["Strensall"],
    "St Mary le Ghyll, Barnoldswick, Lancashire": towerNames["Barnoldswick"],
    "All Saints, Broughton in Craven, North Yorkshire": towerNames["Broughton in Craven"],
    "All Saints, Holme on Spalding Moor, East Riding of Yorkshire": towerNames["Broughton in Craven"],
    "All Saints, Inveraray, Argyll": towerNames["Inveraray"],
    "All Saints, Kirby Hill, North Yorkshire": towerNames["Kirby Hill"],
    "All Saints, Pontefract, West Yorkshire": towerNames["Pontefract"],
    "All Saints, Rufforth, North Yorkshire": towerNames["Rufforth"],
    "All Saints, Thorpe Arch, West Yorkshire": towerNames["Thorpe Arch"],
    "All Saints, Yatesbury, Wiltshire": towerNames["Yatesbury"],
    "East Campus, University of York, North Yorkshire": towerNames["East Campus"],
    "Campus East Stall 10, University of York Open Day, ": towerNames["East Campus"],
    "Melrose School, Brewster, New York": towerNames["Brewster"],
    "Red Light Ring, Dunkirk, Nottinghamshire": towerNames["Dunkirk"],
    "St Giles, Pontefract, West Yorkshire": towerNames["Pontefract (St Giles)"],
    "St Giles, West Bridgford, Nottinghamshire": towerNames["West Bridgford"],
    "St Helen, Ainderby Steeple, North Yorkshire": towerNames["Ainderby Steeple"],
    "St Helen, Escrick, North Yorkshire": towerNames["Escrick"],
    "St James the Apostle, Birstwith, North Yorkshire": towerNames["Birstwith"],
    "St John's College, York, North Yorkshire": towerNames["St John's College"],
    "St Lawrence, Seale, Surrey": towerNames["Seale"],
    "St Martin of Tours, Bilborough, Nottinghamshire": towerNames["Bilborough"],
    "St Mary the Virgin, Chieveley, Berkshire": towerNames["Chieveley"],
    "St Mary, Beenham, Berkshire": towerNames["Beenham"],
    "St Mary, Wath juxta Ripon, North Yorkshire": towerNames["Wath"],
    "St Mary, Weldon, Northamptonshire": towerNames["Weldon"],
    "St Matthew, Midgham, Berkshire": towerNames["Midgham"],
    "St Michael, Pirbright, Surrey": towerNames["Pirbright"],
    "St Michael, Yorktown, Surrey": towerNames["Yorktown"],
    "St Nicholas, Chiswick, Greater London": towerNames["Chiswick"],
    "St Nicolas, Newbury, Berkshire": towerNames["Newbury"],
    "St Oswald, Horton in Ribblesdale, North Yorkshire": towerNames["Horton in Ribblesdale"],
    "St Peter, Marton in Craven, North Yorkshire": towerNames["Marton in Craven"],
    "St Peter, Upper Helmsley, North Yorkshire": towerNames["Upper Helmsley"],
    "St Wilfrids, Harrogate, North Yorkshire": towerNames["Harrogate"],
    "The Ascension, Rochester, New York": towerNames["Rochester"],
    ", Ringing Room, UK": towerNames["Ringing Room"],
    ", Richmond, North Yorkshire": "Richmond, North Yorkshire",
    "Lichfield Diocesan Mobile Belfry, Baskerville House, Staffordshire": towerNames["Baskerville"],
    "532 Norwich Road (The Vestey Ring), Ipswich, Suffolk": towerNames["532 Norwich Road"],
    "35 Willis Street, York, North Yorkshire": towerNames["35 Willis Street"],
    "61 Fox Street, Warrington, ": towerNames["61 Fox Street"],
}
