document.write('<section id="splitter" class="about bg-ycgGreen roomy-5">\n')
document.write('<div class="container">\n')
document.write('<div class="row">\n')
document.write('<div class="pageDivide">\n')
document.write('<br>\n')
document.write('</div>')
document.write('</div>')
document.write('</div>')
document.write('</section>')
