name: quote-submitted

on:
  repository_dispatch:
    types: [ quote-submitted ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Set env
        run: |
          echo "INPUT_USERNAME="${{ github.event.client_payload.username }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_NAME1="${{ github.event.client_payload.quote.name1 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_QUOTE1="${{ github.event.client_payload.quote.quote1 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_NAME2="${{ github.event.client_payload.quote.name2 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_QUOTE2="${{ github.event.client_payload.quote.quote2 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_NAME3="${{ github.event.client_payload.quote.name3 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_QUOTE3="${{ github.event.client_payload.quote.quote3 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_NAME4="${{ github.event.client_payload.quote.name4 }}"" >> $GITHUB_ENV
          echo "INPUT_QUOTE_QUOTE4="${{ github.event.client_payload.quote.quote4 }}"" >> $GITHUB_ENV
          echo "INPUT_ID="${{ github.run_id }}-${{ github.run_attempt }}"" >> $GITHUB_ENV

      - name: quote submitted python code
        run: |
          python quotes/quoteSubmitted.py

      - name: Send email
        uses: cinotify/github-action@main
        with:
          to: 'william.j.lake2000@gmail.com'
          subject: 'building main'
          body: 'This is a notification from GitHub actions.'


      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "rebuild database" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
